### ISSUE TITLE
Support second level caching for EF

### ISSUE THREAD

**Issue by bahmani00** [codemvp/accountgo#12]
EntityFramework.Cache nuget speeds up the application like a hell it's great to have it.
https://efcache.codeplex.com/

**Comment by codebangla** [comment]
@bahmani00 how is EFcache performance in comparison with Dapper?

**Comment by bahmani00** [comment]
Im glad you mentioned Dapper. I've never used Dapper but I did a search and found 
http://www.exceptionnotfound.net/dapper-vs-entity-framework-vs-ado-net-performance-benchmarking/
and from there there is a benchmarking tool https://github.com/exceptionnotfound/ORMBenchmarksTest which gives u the comparsion. I did run it which the following inputs:
# of Test Runs: 10
# of Sports per Run: 10
# of Teams per Sport: 10
# of Players per Team: 10

the result is;

EntityFramework Results
Run #   Player by ID            Players per Team                Teams per Sport
0               21.9                    16.3                    55.4
1               32.3                    15.9                    40.2
2               31.1                    17.6                    39.3
3               30.7                    14.2                    23.5
4               14.1                    14.2                    23.6
5               15.1                    14.3                    27.8
6               14.7                    23.1                    23.6
7               15                      14.2                    23.5
8               15.4                    14.1                    23.2
9               15.2                    14.2                    23.5
ADONET Results
Run #   Player by ID            Players per Team                Teams per Sport
0               9.4                     9                       11.2
1               9.1                     9.1                     29.8
2               9.9                     25.6                    10.4
3               8.2                     9.3                     10.2
4               8.2                     9.1                     10.6
5               13.1                    8.8                     10.7
6               9.2                     8.8                     10.2
7               8.8                     11.9                    10.3
8               9.1                     8.3                     11.6
9               8.7                     8.8                     10.4
Dapper Results
Run #   Player by ID            Players per Team                Teams per Sport
0               31                      28.7                    13.5
1               20                      16.3                    27.6
2               9.5                     9.1                     11.9
3               10.6                    9.1                     12.3
4               9.6                     9.7                     11.7
5               9.3                     9                       12.3
6               9.8                     9.2                     12.5
7               10.1                    9.9                     11.8
8               9.1                     10.3                    12.7
9               9                       9.9                     11.7

which literally says:
1. ADO.net 
2. Dapper
3. nHibernate
4. EF

The result provoked me to consider seriously Dapper.Net not now but for later on.

**Comment by codemvp** [comment]
apply the EFCache from bahmani.
