### ISSUE TITLE
Fix the Print buttons

### ISSUE THREAD

**Issue by codebangla** [codemvp/accountgo#17]
Print buttons(i.e SO) in all pages are not currently functional. All the print buttons need fixes.

**Comment by bahmani00** [comment]
I fixed this issue, if I remember correctly in _Layout.cshtml:
    <script>
        var rootSite = '@HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority)@Url.Content("~/")'; 
    </script>

and in PrintPdf method
window.open(rootSite + 'Reports/' + action + '?id=' + id, '_blank');

**Comment by codemvp** [comment]
Apply the fix from bahmani00 fork
