### ISSUE TITLE
Demo User Creation Not working

### ISSUE THREAD

**Issue by montyaahad** [codemvp/accountgo#6]
After build and running you application, I couldn't login to the system. After searching I found the first user creation code was commented out in "Source/Web/App_Start/IdentityConfig.cs" file -

`//var user = new ApplicationUser { UserName = "admin", Email = "admin@email.com" };`
`//var result = manager.Create(user, "P@ssw0rd1");`

After activating these two lines, user related tables in database had been created. Also, the demo user also been created.

**Comment by codemvp** [comment]
Thanks monty..I merge your comment.
